"""Build inspectable G1–G4 tables from recorded campaign artifacts."""
import argparse
from collections import Counter
from datetime import datetime,timezone
from .generate import read
from .campaign_metrics import BASE,collect
from .coverage_results import build as coverage,VALID
from .negative_audit import audit as negatives
from .usage import report as usage

def build(final=False):
    data=collect();cov=coverage();neg=negatives();cost=usage(BASE);g1=read(BASE/'g1.json')
    prior=(BASE/'report.md').read_text();g4=prior[prior.index('## G4: evaluator reliability'):]
    # Keep the established G4 analysis, replacing its former cost/progress tail.
    for marker in ['## Cost','## Current','## Remaining','## Reproducibility']:
        if marker in g4:g4=g4.split(marker)[0].rstrip()+'\n'
    gen=[r for r in data['cases'] if r['construction_type']=='clean_generation'];mut=[r for r in data['cases'] if r['construction_type']!='clean_generation']
    accepted=[r for r in gen if r['construction_status']=='review_pass'];audited=[r for r in accepted if r['manual_review']];valid=[r for r in audited if r['manual_review']['validity'] in VALID]
    currentbugs=[r for r in gen if not r.get('outcome_informed_revision') and r['manual_review'] and r['manual_review']['validity'] in VALID and 'confirmed' in r['manual_review'].get('grounding_flags',{}).values()]
    findings=[x for x in data['confirmed_findings_all_versions'] if x['validity'] in VALID];distinct={x['case_id'] for x in findings}
    mode={'single':'single','multiple':'multiple','underspecified':'underspecified','absent':'absent'}
    lines=['# Slack G1–G4 campaign'+('' if final else ' — running checkpoint'),'','Updated '+datetime.now(timezone.utc).isoformat()+'.','',
        ('The bounded campaign is complete. Unresolved and unrealized attempts are retained as outcomes, not successful tests.' if final else 'Construction recovery and execution are still in progress. Counts below are a reproducible checkpoint, not final results.'),'',
        'The domain model, baseline cards, baseline ground truth and manual audits are human/Codex work. Writer, compiler, reviewer, solver and evaluator calls use Sonnet 5 on Bedrock. Baseline run labels enter only G4. The earlier `pilot_01` is preserved separately and excluded from these yields. See [methods](methods.md) and [all cases](campaign_results.md).','',
        '## G1: baseline design','','| Measure | Result |','|---|---:|',
        '| Tasks / tasks with obligations | 59 / 58 |','| Grounding obligations | 198 |','| Native assertions: full / partial / unchecked | 74 / 37 / 87 |','| Complete routes | 12 / 174 |','| Identifying attributes | 13 / 26 |','| Entity–resolution modes | 12 / 28 |','| Representative capability-limit probes | 0 / 25 |','',
        'The requested modes are 129 single, 34 jointly intended collections, 11 absent and 20 underspecified. Four optional delegated subsets remain separate. Counts concern the benchmark design, not whether a solver followed a particular trajectory. [Counts](g1.json); [baseline mapping](../../../grounding/slack_coverage/baseline_mapping_review.md); [catalog](../../../grounding/slack_coverage/catalog.md).','',
        '## G2: native false passes and mutation','','Fresh structured assessments followed by manual source-evidence confirmation found **9 grounding violations in 7 of the 47 native-accepted baseline runs**. This is a confirmed-discovery count, not exhaustive recall. No ground-truth run labels were supplied to that discovery process.','',
        '| Native-accepted task | Confirmed obligations |','|---|---|','| slack_67 | O1 |','| slack_74 | O1 |','| slack_95 | O1 |','| slack_97 | O4 |','| slack_101 | O2, O5, O8 |','| slack_107 | O5 |','| slack_110 | O7 |','',
        '[Manual confirmations and evidence](g2_native_manual_review.json). Six source assignments were fixed for environment-only mutation, preserving their prompts and intended references. Failed/no-op intermediate patches remain in the attempt history.','',
        '| Mutation | Manual final validity / quality | Execution | Original focal judgment → mutant |','|---|---|---|---|']
    for r in mut:
        a=r['manual_review'] or {};old=r.get('original_focal_judgment','unknown');new=r.get('mutant_focal_judgment') or 'not assessed'
        lines.append(f"| [{r['case_id']}](construction/{r['case_id']}/case.json) | {a.get('validity','unreviewed')} / {a.get('quality','—')} | {r['execution_status']} | {old} → {new} |")
    validmut=[r for r in mut if r['manual_review'] and r['manual_review']['validity'] in VALID and r['execution_status']=='completed']
    transitions=[r for r in validmut if r.get('candidate_focal_transition')]
    lines+=['',f'Among the **{len(validmut)} accepted completed mutations**, there are **{len(transitions)} observed correct-to-incorrect focal transitions**. These are focal-obligation comparisons; a source run can contain independent failures. This pilot does not establish that mutation increases failure probability. Several negatives are valid but weak (they differ in more than one condition); the owner-as-nonadmin and root-message-versus-thread-reply boundaries are withheld from definitive mutation claims. [Manual review](manual_review.json).','',
        '## G3: generation','','The fixed route plan has 174 assignments, including six labeled development/calibration cases. Repairs use native conversation continuations. Prompt and harness changes during development are preserved per invocation; this is not a held-out evaluation of one frozen authoring prompt.','',
        '| Stage / result | Cases |','|---|---:|',f'| Planned complete routes | {len(gen)} |']
    for status,n in sorted(Counter(r['construction_status'] for r in gen).items()):lines.append(f'| Construction: {status} | {n} |')
    for status,n in sorted(Counter(r['execution_status'] for r in gen).items()):lines.append(f'| Execution: {status} | {n} |')
    lines += [f'| Model-accepted current cases manually audited | {len(audited)} / {len(accepted)} |',f'| Audited cases accepted as valid tasks, including shorter routes | {len(valid)} / {len(audited)} |',f'| Accepted valid-task yield over all planned assignments | {len(valid)} / {len(gen)} |',f'| Current valid generated cases with confirmed grounding failures | {len(currentbugs)} |',f'| Distinct generated case IDs with confirmed failures across preserved valid versions | {len(distinct)} |','',
        f'Stage counts are not a strictly nested funnel: a case can retain an earlier execution after a later construction revision fails. Coverage and current primary discoveries require a version-matched accepted case. {sum(r.get("solver_termination")=="turn_limit" for r in data["cases"])} recorded current solver episodes ended at the turn limit; an evaluator reporting completed means its assessment completed, not that the solver succeeded. One revised case (G-R094) received earlier solver-answer detail in manual construction feedback. It is outcome-informed and excluded from the primary current failure/coverage counts; the original shorter-route case remains separate. [Provenance exception](provenance_exceptions.json). A valid shorter-route task does not earn its assigned longer route. API eligibility is separate from what the prompt asks. The following counts are conservative, version-matched manual coverage lower bounds; no automatic prefix/subpath credit is used.','',
        '| Requirement family | Baseline | Generated requested designs | Generated API-qualified solver executions | Baseline ∪ executed generation |','|---|---:|---:|---:|---:|']
    basecounts={'routes':12,'attributes':13,'modes':12,'capability_limitations':0}
    for key,label in [('routes','Complete routes'),('attributes','Identifying attributes'),('modes','Entity–resolution modes'),('capability_limitations','Capability limits')]:
        den=cov['denominators'][key];requested=cov['requested_design']['coverage'][key];executed=cov['api_qualified_executed']['coverage'][key];union=cov['api_qualified_executed']['with_baseline'][key]
        lines.append(f'| {label} | {basecounts[key]}/{den} | {requested}/{den} | {executed}/{den} | {union}/{den} |')
    lines += ['', '[Cell-level evidence](coverage_results.json). A solver execution with unresolved evaluator serialization is still an execution, but is not counted as a complete automated assessment. No dedicated capability-probe generation was completed; incidental unavailable asks and manual API investigations receive no automatic capability credit.','',
        f"The compiled-query diagnostic finds at least one declared negative admitted by relaxing exactly one filter in **{neg['summary']['with_declared_one_filter_negative']}/{neg['summary']['cases']} model-accepted cases** (generation and mutation combined). This is evidence of a concrete near-miss distinction, not a semantic-validity or difficulty certificate. Missing-edge negatives can escape this diagnostic. [Negative audit](negative_audit.json).",'',
        '| Confirmed current generated failure | Requested mode | Evidence |','|---|---|---|']
    for r in currentbugs:
        cid=r['case_id'];lines.append(f"| [{cid}](construction/{cid}/case.json) | {r['assigned_mode']} | [Response](execution/{cid}/assessment/sources/response.json), [assessment](execution/{cid}/assessment/assessment.json) |")
    lines+=['', 'Common confirmed failures include false empty-set reports for existing reactions, silently dropping a condition, and choosing between equally matching people using unrequested email/domain preferences. Manual review also rejects evaluator flags: G-R212 explicitly acknowledges the missing channel-membership condition and distinguishes supplemental information, so its flag is not a confirmed failure. G-R059 remains withheld over the wording boundary between a Slack reaction and a textual emoji reply. The earlier G-R062 flag rested on an unjustifiably narrow generated card.','',
        'The full [manual audit](manual_review.json) and [preserved findings](campaign_results.json) distinguish current cases, old versions, invalid boundaries and qualified shorter-route discoveries. These flag-focused confirmations do not measure generation-evaluator recall. Read-only status and partial-performance disagreements are not silently promoted into grounding failures.','',g4.rstrip(),'','## Cost, limitations and reproduction','',
        f"Recorded invocations: **{cost['invocations']:,}**. Native usage totals: **{cost['tokens'].get('input_tokens',0):,} input**, **{cost['tokens'].get('output_tokens',0):,} output**, **{cost['tokens'].get('cache_creation_input_tokens',0):,} cache-write**, and **{cost['tokens'].get('cache_read_input_tokens',0):,} cache-read tokens**. The historical-rate estimate is **${cost['estimated_cost_usd']:,.2f}**, not a Bedrock invoice or provider-reported dollar charge. **{len(cost['usage_unavailable'])}** recorded invocations lack returned usage; they are listed rather than treated as free. [Usage totals and rates](usage_summary.json); [every recorded call](usage_ledger.json).",'',
        'Input/context repetition is substantial: authoring/review conversations repeatedly carry base seed, source API information and cumulative compilation context. Solver caching is recorded; the authoring adapter did not use prompt caching in this campaign. These costs include unsuccessful, repair and transport attempts with returned usage; they exclude the already-existing baseline solver run costs and manual/Codex labor.','',
        'The main limitations are incomplete route realization, secondary-workspace discovery limits, semantic annotation errors, and uneven negative-example strength. Some long absent queries can be settled at an early empty join and therefore provide a weaker depth challenge. The shared seed leads to repeated names/topics. Role-report tasks can expose only the distinctions supported by API flags; identity-grounding findings do not certify every reported role attribute. [Runtime qualifications](runtime_qualifications.md).','',
        '[Final mechanical/provenance checks](final_validation.json) verify the accepted artifacts, version-matched manual audits and evidence links. The experiment provides results for all four goals; it does not claim complete coverage, perfect generation, a mutation-induced failure increase, or held-out oracle generalization. Source cards and oracle policies were developed with some of these baseline cases.','',
        'To rebuild this report without model calls, run `python -m grounding.slack_campaign.build_report'+(' --final' if final else '')+'` with the configured project Python environment. [Methods](methods.md) explain the authoring, validation, runtime and provenance boundaries. All native requests/responses and available summarized thinking blocks remain beside their stage artifacts.','']
    (BASE/'report.md').write_text('\n'.join(lines))
    print('Wrote',BASE/'report.md')
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--final',action='store_true');a=p.parse_args();build(a.final)
