"""Every table of autogen_02's report, generated from the run data.

    python grounding/runs/fact_coverage_02/launch.py grounding.runs.autogen_02.kit.tables > grounding/runs/autogen_02/tables.md
"""
from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

from grounding.runs.autogen_02.kit import policy_analysis
from grounding.runs.autogen_02.kit.sampler import FAIL, PASS, lower_bound, upper_bound

STUDY = Path(__file__).resolve().parents[1]
RUNS = STUDY / "runs"


def md(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in rows]
    return "\n".join(out)


def bounds(k, n):
    return f"[{lower_bound(k, n):.2f}, {upper_bound(k, n):.2f}]" if n else "-"


def phase1():
    res = policy_analysis.analyse()
    out = ["## Phase 1: the per-fact policy variants of fact_coverage_02's 18 scenarios (my labels)\n"]
    rows = []
    for mode in ("absence", "underspecified", "clone"):
        for domain in ("box", "calendar", "linear", "slack"):
            fs = [f for f in res["facts"] if f["mode"] == mode and f["domain"] == domain]
            if not fs:
                continue
            t1 = [f["t1"] in FAIL for f in fs if f["t1"] in FAIL | PASS]
            spread = Counter(f"{f['fails']}/3" for f in fs if f["usable"] == 3)
            rows.append([mode, domain, len(fs), f"{sum(f['fails'] for f in fs)}/{sum(f['usable'] for f in fs)}",
                         f"{sum(t1)}/{len(t1)}", bounds(sum(t1), len(t1)),
                         ", ".join(f"{k}: {v}" for k, v in sorted(spread.items(), reverse=True))])
    out.append(md(["Mode", "Domain", "Variants", "Failing trials", "Trial 1 fails", "90% bounds (t1)",
                   "Variants by failures in 3 trials"], rows))
    readings = Counter(f["reading"] for f in res["facts"] if f["mode"] == "absence")
    out.append("\n**The D4 pair reading of the absence twins** (the fact's probes in autogen_01's same-day control "
               "run, 3 trials each): " + ", ".join(f"{k}: {v}" for k, v in readings.most_common()) + ".\n")
    rows = [[f["variant"], f["fact"], f.get("family") or "", f"{f['fails']}/{f['usable']}",
             f"{f.get('probe_fails', '')}/{f.get('probe_n', '')}" if f["mode"] == "absence" else "",
             f.get("reading", "") if f["mode"] == "absence" else f"{f.get('matches')} matches, "
             f"{f.get('other_near_misses')} other near misses"] for f in res["facts"]]
    out.append(md(["Variant", "Fact", "Family", "Fails", "Probe fails", "Reading / match set"], rows))
    return "\n".join(out)


def construction():
    out = ["## Construction: how many policy variants derive\n"]
    rows = []
    idx = json.loads((RUNS / "phase1" / "index.json").read_text())
    by_form = defaultdict(Counter)
    for v in idx.values():
        by_form[v.get("form")]["accepted" if v.get("accepted") else "not"] += 1
    for form, c in by_form.items():
        rows.append(["exemplars (Phase 1, by hand)", form, c["accepted"], c["not"]])
    for name, form in (("phase3_dropf", "underspecified (automated)"), ("phase3_clone", "clone (automated)"),
                       ("phase2_cal2_dropf", "underspecified (automated, exemplars, cal2)")):
        folder = RUNS / name
        if folder.exists():
            st = Counter(json.loads(p.read_text())["status"] for p in folder.glob("*/record.json"))
            rows.append([name, form, st.get("accepted", 0), ", ".join(f"{k} {v}" for k, v in st.items()
                                                                      if k != "accepted")])
    out.append(md(["Source", "Variant", "Derived", "Not derived"], rows))
    return "\n".join(out)


def costs():
    out = ["## Muse usage per run (tokens and cost at list and billed rates)\n"]
    rows = []
    for calls in sorted(RUNS.glob("*/calls.jsonl")):
        n = inp = cached = outp = 0
        lst = billed = secs = 0.0
        for line in calls.read_text().splitlines():
            r = json.loads(line)
            n += 1
            inp += r.get("input_tokens") or 0
            cached += r.get("cache_read_input_tokens") or 0
            outp += r.get("output_tokens") or 0
            lst += r.get("cost_usd_list_price") or r.get("total_cost_usd") or 0
            billed += r.get("cost_usd_billed") or 0
            secs += r.get("seconds") or 0
        rows.append([calls.parent.name, n, f"{inp:,}", f"{cached:,}", f"{outp:,}", f"${lst:.2f}", f"${billed:.3f}",
                     f"{secs / 3600:.1f}"])
    out.append(md(["Run", "Calls", "Input tokens", "Cached", "Output tokens", "List", "Billed", "Agent hours"],
                  rows))
    return "\n".join(out)


def main():
    print("# autogen_02 tables\n\nGenerated by `kit/tables.py` from the run data.\n")
    for section in (phase1, construction, costs):
        try:
            print(section())
        except Exception as exc:  # a section whose data is not there yet
            print(f"(section {section.__name__} unavailable: {exc})")
        print()


if __name__ == "__main__":
    main()
