# Core business logic for Calendar API
from .errors import (
    CalendarAPIError,
    NotFoundError,
    CalendarNotFoundError,
    EventNotFoundError,
    AclNotFoundError,
    SettingNotFoundError,
    ChannelNotFoundError,
    ValidationError,
    RequiredFieldError,
    InvalidFieldError,
    DuplicateError,
    ForbiddenError,
    UnauthorizedError,
    PreconditionFailedError,
    GoneError,
    SyncTokenExpiredError,
    RateLimitedError,
    InternalError,
    TooManyCalendarsError,
    GroupTooBigError,
    error_response,
    validation_error_response,
    not_found_response,
    handle_exception,
)

from .utils import (
    generate_event_id,
    generate_calendar_id,
    generate_ical_uid,
    generate_acl_rule_id,
    generate_channel_id,
    generate_resource_id,
    generate_sync_token,
    generate_etag,
    generate_version_etag,
    etags_match,
    parse_rfc3339,
    format_rfc3339,
    parse_date,
    format_date,
    now_rfc3339,
    calendar_now,
    REPLICA_NOW_ENV,
    is_all_day_event,
    extract_datetime,
    PageToken,
    paginate_list,
    expand_recurrence,
    build_list_response,
    build_free_busy_response,
    validate_event_id,
    validate_calendar_id,
    normalize_calendar_id,
    # Recurring instance helpers
    parse_instance_id,
    format_instance_id,
    parse_original_start_time,
    build_original_start_time,
)

from .serializers import (
    serialize_calendar,
    serialize_calendar_list,
    serialize_calendar_list_entry,
    serialize_event,
    serialize_events_list,
    serialize_attendee,
    serialize_acl_rule,
    serialize_acl_list,
    serialize_setting,
    serialize_settings_list,
    serialize_channel,
    serialize_colors,
    serialize_free_busy,
    serialize_error,
    serialize_event_instances,
)

from .batch_parser import (
    BatchParseError,
    BatchPart,
    ParsedBatchRequest,
    extract_boundary,
    parse_batch_request,
    parse_content_id,
    parse_inner_http_request,
    merge_query_params,
    merge_headers,
)

from .batch_builder import (
    BatchResponsePart,
    build_batch_response,
    format_inner_response,
    format_response_content_id,
    get_status_text,
)

__all__ = [
    # Errors
    "CalendarAPIError",
    "NotFoundError",
    "CalendarNotFoundError",
    "EventNotFoundError",
    "AclNotFoundError",
    "SettingNotFoundError",
    "ChannelNotFoundError",
    "ValidationError",
    "RequiredFieldError",
    "InvalidFieldError",
    "DuplicateError",
    "ForbiddenError",
    "UnauthorizedError",
    "PreconditionFailedError",
    "GoneError",
    "SyncTokenExpiredError",
    "RateLimitedError",
    "InternalError",
    "TooManyCalendarsError",
    "GroupTooBigError",
    "error_response",
    "validation_error_response",
    "not_found_response",
    "handle_exception",
    # Utils
    "generate_event_id",
    "generate_calendar_id",
    "generate_ical_uid",
    "generate_acl_rule_id",
    "generate_channel_id",
    "generate_resource_id",
    "generate_sync_token",
    "generate_etag",
    "generate_version_etag",
    "etags_match",
    "parse_rfc3339",
    "format_rfc3339",
    "parse_date",
    "format_date",
    "now_rfc3339",
    "is_all_day_event",
    "extract_datetime",
    "PageToken",
    "paginate_list",
    "expand_recurrence",
    "build_list_response",
    "build_free_busy_response",
    "validate_event_id",
    "validate_calendar_id",
    "normalize_calendar_id",
    # Recurring instance helpers
    "parse_instance_id",
    "format_instance_id",
    "parse_original_start_time",
    "build_original_start_time",
    # Serializers
    "serialize_calendar",
    "serialize_calendar_list",
    "serialize_calendar_list_entry",
    "serialize_event",
    "serialize_events_list",
    "serialize_attendee",
    "serialize_acl_rule",
    "serialize_acl_list",
    "serialize_setting",
    "serialize_settings_list",
    "serialize_channel",
    "serialize_colors",
    "serialize_free_busy",
    "serialize_error",
    "serialize_event_instances",
    # Batch Parser
    "BatchParseError",
    "BatchPart",
    "ParsedBatchRequest",
    "extract_boundary",
    "parse_batch_request",
    "parse_content_id",
    "parse_inner_http_request",
    "merge_query_params",
    "merge_headers",
    # Batch Builder
    "BatchResponsePart",
    "build_batch_response",
    "format_inner_response",
    "format_response_content_id",
    "get_status_text",
]
